### ISSUE TITLE
Create a subset the data from SA moorings. 

### ISSUE THREAD

**Issue by ribeiron** [oceanhackweek/ohw23_proj_SAupwelling#1]
•	Create code where we can access the different moorings. 
•	Create a map where we can see the locations of the SA moorings we are using (+NRS station) with a bathymetry background. 

I would like to use the SA coastal moorings and the SA NRS station. 
- SA coastal moorings that are active: SAM8SG, SAM5CB
- NRS station: NRSKAI
- SA coastal moorings that are not active but have data available: SAM2CP, SAM6IS, SAM3MS, SAM7DS

In theory, we can access data from all of those, but I haven't tried that yet for all of them. 
Here there is a code that gets data from the NRS station in SA stored in the AODN, from the "IMOS bucket": https://github.com/ribeiron/ohw22-proj-plot_this_and_that/blob/main/notebooks/IMOS_buoy_plot_anomaly_NRS_SA.ipynb

But SA has other coastal moorings there that can be used. On the AODN Portal, you can see how many there are https://portal.aodn.org.au/search. 

In the IMOS website there is also more info on them and the moorings code names: https://imos.org.au/facilities/nationalmooringnetwork/samoorings

Here is the IMOS bucket, so you can understand a little better how the file structure is http://imos-data.s3-website-ap-southeast-2.amazonaws.com/?prefix=IMOS/ANMN/

**Comment by vinisalazar** [comment]
@ribeiron can we close this one?

**Comment by seaCatKim** [comment]
map uploaded
